### ISSUE TITLE
Incomplete line in log file

### ISSUE THREAD

**Issue by jforissier** [jbech-linaro/ibart#9]
In https://optee.mooo.com:5000/logs/OP-TEE/optee_os/3268/316516449/1b0a09cc2a0bda6b8f4810376353dd481fbb84be#01-hikey6220-build:
```
     1:  IBART $ 
<EVEL=1 CFG_LOCKDEP=y CFG_CORE_MBEDTLS_MPI=y;echo $?
     2:  mkdir -p /home/optee/devel/hikey/build/../out
```

1. The command line is incomplete
2. The `echo $?` does not display `0` before line 2

The first point is the real issue because it makes it impossible to know which build flags have been set, and therefore to reproduce the build locally.

**Comment by jockebech** [comment]
@jforissier don't be afraid, I'm playing with GitHub workflows / actions  ... to eventually present a RFC to OP-TEE later also, if/when I know how to configure it correctly. See this a bit as the playground for this :)

**Comment by jforissier** [comment]
@jbech-linaro no problem, thanks for explaining :)

**Comment by jockebech** [comment]
Alright, so the "add a comment" thing apparently didn't work as supposed to. Testing continues.
